import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});



export const metadata: Metadata = {
  title: "Health Zenix App",
  description: "Generated by rakibul hasan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      className="hydrated"
      data-arp=""
    >
      <body
        className={`${ubuntu.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
